// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: ctrl.proto

package ctrlpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddrPair struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LocalAddr     string                 `protobuf:"bytes,1,opt,name=localAddr,proto3" json:"localAddr,omitempty"`
	RemoteAddr    string                 `protobuf:"bytes,2,opt,name=remoteAddr,proto3" json:"remoteAddr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddrPair) Reset() {
	*x = AddrPair{}
	mi := &file_ctrl_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddrPair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddrPair) ProtoMessage() {}

func (x *AddrPair) ProtoReflect() protoreflect.Message {
	mi := &file_ctrl_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddrPair.ProtoReflect.Descriptor instead.
func (*AddrPair) Descriptor() ([]byte, []int) {
	return file_ctrl_proto_rawDescGZIP(), []int{0}
}

func (x *AddrPair) GetLocalAddr() string {
	if x != nil {
		return x.LocalAddr
	}
	return ""
}

func (x *AddrPair) GetRemoteAddr() string {
	if x != nil {
		return x.RemoteAddr
	}
	return ""
}

type Tunnel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	User          string                 `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Addr          string                 `protobuf:"bytes,3,opt,name=addr,proto3" json:"addr,omitempty"`
	AddressPair   map[string]*AddrPair   `protobuf:"bytes,4,rep,name=address_pair,json=addressPair,proto3" json:"address_pair,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Pw            string                 `protobuf:"bytes,5,opt,name=pw,proto3" json:"pw,omitempty"`
	Privkey       []byte                 `protobuf:"bytes,6,opt,name=privkey,proto3" json:"privkey,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tunnel) Reset() {
	*x = Tunnel{}
	mi := &file_ctrl_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tunnel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tunnel) ProtoMessage() {}

func (x *Tunnel) ProtoReflect() protoreflect.Message {
	mi := &file_ctrl_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tunnel.ProtoReflect.Descriptor instead.
func (*Tunnel) Descriptor() ([]byte, []int) {
	return file_ctrl_proto_rawDescGZIP(), []int{1}
}

func (x *Tunnel) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Tunnel) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *Tunnel) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Tunnel) GetAddressPair() map[string]*AddrPair {
	if x != nil {
		return x.AddressPair
	}
	return nil
}

func (x *Tunnel) GetPw() string {
	if x != nil {
		return x.Pw
	}
	return ""
}

func (x *Tunnel) GetPrivkey() []byte {
	if x != nil {
		return x.Privkey
	}
	return nil
}

type Fwd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Parent        *Tunnel                `protobuf:"bytes,2,opt,name=parent,proto3" json:"parent,omitempty"`
	Addrs         *AddrPair              `protobuf:"bytes,3,opt,name=addrs,proto3" json:"addrs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Fwd) Reset() {
	*x = Fwd{}
	mi := &file_ctrl_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Fwd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fwd) ProtoMessage() {}

func (x *Fwd) ProtoReflect() protoreflect.Message {
	mi := &file_ctrl_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Fwd.ProtoReflect.Descriptor instead.
func (*Fwd) Descriptor() ([]byte, []int) {
	return file_ctrl_proto_rawDescGZIP(), []int{2}
}

func (x *Fwd) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Fwd) GetParent() *Tunnel {
	if x != nil {
		return x.Parent
	}
	return nil
}

func (x *Fwd) GetAddrs() *AddrPair {
	if x != nil {
		return x.Addrs
	}
	return nil
}

type PsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PsRequest) Reset() {
	*x = PsRequest{}
	mi := &file_ctrl_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PsRequest) ProtoMessage() {}

func (x *PsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ctrl_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PsRequest.ProtoReflect.Descriptor instead.
func (*PsRequest) Descriptor() ([]byte, []int) {
	return file_ctrl_proto_rawDescGZIP(), []int{3}
}

type PsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fwds          []*Fwd                 `protobuf:"bytes,1,rep,name=fwds,proto3" json:"fwds,omitempty"`
	Errors        []string               `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PsResponse) Reset() {
	*x = PsResponse{}
	mi := &file_ctrl_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PsResponse) ProtoMessage() {}

func (x *PsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ctrl_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PsResponse.ProtoReflect.Descriptor instead.
func (*PsResponse) Descriptor() ([]byte, []int) {
	return file_ctrl_proto_rawDescGZIP(), []int{4}
}

func (x *PsResponse) GetFwds() []*Fwd {
	if x != nil {
		return x.Fwds
	}
	return nil
}

func (x *PsResponse) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

type OpenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tunnels       []*Tunnel              `protobuf:"bytes,1,rep,name=tunnels,proto3" json:"tunnels,omitempty"`
	Errors        []string               `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenRequest) Reset() {
	*x = OpenRequest{}
	mi := &file_ctrl_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenRequest) ProtoMessage() {}

func (x *OpenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ctrl_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenRequest.ProtoReflect.Descriptor instead.
func (*OpenRequest) Descriptor() ([]byte, []int) {
	return file_ctrl_proto_rawDescGZIP(), []int{5}
}

func (x *OpenRequest) GetTunnels() []*Tunnel {
	if x != nil {
		return x.Tunnels
	}
	return nil
}

func (x *OpenRequest) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

type OpenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OpenedIds     []string               `protobuf:"bytes,1,rep,name=opened_ids,json=openedIds,proto3" json:"opened_ids,omitempty"`
	Errors        []string               `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenResponse) Reset() {
	*x = OpenResponse{}
	mi := &file_ctrl_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenResponse) ProtoMessage() {}

func (x *OpenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ctrl_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenResponse.ProtoReflect.Descriptor instead.
func (*OpenResponse) Descriptor() ([]byte, []int) {
	return file_ctrl_proto_rawDescGZIP(), []int{6}
}

func (x *OpenResponse) GetOpenedIds() []string {
	if x != nil {
		return x.OpenedIds
	}
	return nil
}

func (x *OpenResponse) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

type CloseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []string               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseRequest) Reset() {
	*x = CloseRequest{}
	mi := &file_ctrl_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseRequest) ProtoMessage() {}

func (x *CloseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ctrl_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseRequest.ProtoReflect.Descriptor instead.
func (*CloseRequest) Descriptor() ([]byte, []int) {
	return file_ctrl_proto_rawDescGZIP(), []int{7}
}

func (x *CloseRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

type CloseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClosedIds     []string               `protobuf:"bytes,1,rep,name=closed_ids,json=closedIds,proto3" json:"closed_ids,omitempty"`
	Errors        []string               `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseResponse) Reset() {
	*x = CloseResponse{}
	mi := &file_ctrl_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseResponse) ProtoMessage() {}

func (x *CloseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ctrl_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseResponse.ProtoReflect.Descriptor instead.
func (*CloseResponse) Descriptor() ([]byte, []int) {
	return file_ctrl_proto_rawDescGZIP(), []int{8}
}

func (x *CloseResponse) GetClosedIds() []string {
	if x != nil {
		return x.ClosedIds
	}
	return nil
}

func (x *CloseResponse) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

var File_ctrl_proto protoreflect.FileDescriptor

const file_ctrl_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"ctrl.proto\x12\x04ctrl\"H\n" +
	"\bAddrPair\x12\x1c\n" +
	"\tlocalAddr\x18\x01 \x01(\tR\tlocalAddr\x12\x1e\n" +
	"\n" +
	"remoteAddr\x18\x02 \x01(\tR\n" +
	"remoteAddr\"\xfc\x01\n" +
	"\x06Tunnel\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04user\x18\x02 \x01(\tR\x04user\x12\x12\n" +
	"\x04addr\x18\x03 \x01(\tR\x04addr\x12@\n" +
	"\faddress_pair\x18\x04 \x03(\v2\x1d.ctrl.Tunnel.AddressPairEntryR\vaddressPair\x12\x0e\n" +
	"\x02pw\x18\x05 \x01(\tR\x02pw\x12\x18\n" +
	"\aprivkey\x18\x06 \x01(\fR\aprivkey\x1aN\n" +
	"\x10AddressPairEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12$\n" +
	"\x05value\x18\x02 \x01(\v2\x0e.ctrl.AddrPairR\x05value:\x028\x01\"a\n" +
	"\x03Fwd\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12$\n" +
	"\x06parent\x18\x02 \x01(\v2\f.ctrl.TunnelR\x06parent\x12$\n" +
	"\x05addrs\x18\x03 \x01(\v2\x0e.ctrl.AddrPairR\x05addrs\"\v\n" +
	"\tPsRequest\"C\n" +
	"\n" +
	"PsResponse\x12\x1d\n" +
	"\x04fwds\x18\x01 \x03(\v2\t.ctrl.FwdR\x04fwds\x12\x16\n" +
	"\x06errors\x18\x02 \x03(\tR\x06errors\"M\n" +
	"\vOpenRequest\x12&\n" +
	"\atunnels\x18\x01 \x03(\v2\f.ctrl.TunnelR\atunnels\x12\x16\n" +
	"\x06errors\x18\x02 \x03(\tR\x06errors\"E\n" +
	"\fOpenResponse\x12\x1d\n" +
	"\n" +
	"opened_ids\x18\x01 \x03(\tR\topenedIds\x12\x16\n" +
	"\x06errors\x18\x02 \x03(\tR\x06errors\" \n" +
	"\fCloseRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\tR\x03ids\"F\n" +
	"\rCloseResponse\x12\x1d\n" +
	"\n" +
	"closed_ids\x18\x01 \x03(\tR\tclosedIds\x12\x16\n" +
	"\x06errors\x18\x02 \x03(\tR\x06errors2\x9f\x01\n" +
	"\rTunnelService\x12'\n" +
	"\x02Ps\x12\x0f.ctrl.PsRequest\x1a\x10.ctrl.PsResponse\x120\n" +
	"\aOpenFwd\x12\x11.ctrl.OpenRequest\x1a\x12.ctrl.OpenResponse\x123\n" +
	"\bCloseFwd\x12\x12.ctrl.CloseRequest\x1a\x13.ctrl.CloseResponseB\x10Z\x0e./proto;ctrlpbb\x06proto3"

var (
	file_ctrl_proto_rawDescOnce sync.Once
	file_ctrl_proto_rawDescData []byte
)

func file_ctrl_proto_rawDescGZIP() []byte {
	file_ctrl_proto_rawDescOnce.Do(func() {
		file_ctrl_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ctrl_proto_rawDesc), len(file_ctrl_proto_rawDesc)))
	})
	return file_ctrl_proto_rawDescData
}

var file_ctrl_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_ctrl_proto_goTypes = []any{
	(*AddrPair)(nil),      // 0: ctrl.AddrPair
	(*Tunnel)(nil),        // 1: ctrl.Tunnel
	(*Fwd)(nil),           // 2: ctrl.Fwd
	(*PsRequest)(nil),     // 3: ctrl.PsRequest
	(*PsResponse)(nil),    // 4: ctrl.PsResponse
	(*OpenRequest)(nil),   // 5: ctrl.OpenRequest
	(*OpenResponse)(nil),  // 6: ctrl.OpenResponse
	(*CloseRequest)(nil),  // 7: ctrl.CloseRequest
	(*CloseResponse)(nil), // 8: ctrl.CloseResponse
	nil,                   // 9: ctrl.Tunnel.AddressPairEntry
}
var file_ctrl_proto_depIdxs = []int32{
	9, // 0: ctrl.Tunnel.address_pair:type_name -> ctrl.Tunnel.AddressPairEntry
	1, // 1: ctrl.Fwd.parent:type_name -> ctrl.Tunnel
	0, // 2: ctrl.Fwd.addrs:type_name -> ctrl.AddrPair
	2, // 3: ctrl.PsResponse.fwds:type_name -> ctrl.Fwd
	1, // 4: ctrl.OpenRequest.tunnels:type_name -> ctrl.Tunnel
	0, // 5: ctrl.Tunnel.AddressPairEntry.value:type_name -> ctrl.AddrPair
	3, // 6: ctrl.TunnelService.Ps:input_type -> ctrl.PsRequest
	5, // 7: ctrl.TunnelService.OpenFwd:input_type -> ctrl.OpenRequest
	7, // 8: ctrl.TunnelService.CloseFwd:input_type -> ctrl.CloseRequest
	4, // 9: ctrl.TunnelService.Ps:output_type -> ctrl.PsResponse
	6, // 10: ctrl.TunnelService.OpenFwd:output_type -> ctrl.OpenResponse
	8, // 11: ctrl.TunnelService.CloseFwd:output_type -> ctrl.CloseResponse
	9, // [9:12] is the sub-list for method output_type
	6, // [6:9] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_ctrl_proto_init() }
func file_ctrl_proto_init() {
	if File_ctrl_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ctrl_proto_rawDesc), len(file_ctrl_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ctrl_proto_goTypes,
		DependencyIndexes: file_ctrl_proto_depIdxs,
		MessageInfos:      file_ctrl_proto_msgTypes,
	}.Build()
	File_ctrl_proto = out.File
	file_ctrl_proto_goTypes = nil
	file_ctrl_proto_depIdxs = nil
}
